### ISSUE TITLE
add install procedure

### ISSUE THREAD

**Issue by meresmclr** [jswoboda/ISRSpectrum#1]
I have cloned the repositories
ISRSpectrum
PythonISRUtilities
RadarDataSim
and typed

```
git submodule update --init
python setup.py install
```

in each of those directories, without error
then when running
Examples/comparisons.py I get the errors in Python 2 and 3 respectively:
ImportError: No module named const.physConstants
ImportError: No module named `ISRSpectrum.const`

**Comment by jswoboda** [comment]
The const folder is a submodule you have to pull that down after you do the initial pull. I will add some info into the readme to help prevent this.

**Comment by jswoboda** [comment]
I added instructions on how to fix the problem in the readme file. Please check and make sure this works. If this doesn't fix this please open up another issue report.
