### ISSUE TITLE
 module 'ISRSpectrum.ISRSpectrum' has no attribute 'ISRSpectrum'

### ISSUE THREAD

**Issue by yonghuier** [jswoboda/ISRSpectrum#7]
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    ISS2 = ISSnew.ISRSpectrum(centerFrequency = 440.2*1e6, bMag = 0.4e-4, nspec=129, sampfreq=50e3,dFlag=True)
AttributeError: module 'ISRSpectrum.ISRSpectrum' has no attribute 'ISRSpectrum'
(base)

**Comment by habtie-phys** [comment]
> Traceback (most recent call last): File "test.py", line 2, in ISS2 = ISSnew.ISRSpectrum(centerFrequency = 440.2*1e6, bMag = 0.4e-4, nspec=129, sampfreq=50e3,dFlag=True) AttributeError: module 'ISRSpectrum.ISRSpectrum' has no attribute 'ISRSpectrum' (base)

yes, I faced similar problem. Could you kindly fix it please
